blogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.apps import BlogsConfig
from blogs.views import BlogDetailView, BlogListView

app_name = BlogsConfig.name

urlpatterns = [
    path("", cache_page(60)(BlogListView.as_view()), name="blog_page"),
    path("blog_view/<int:pk>/", cache_page(60)(BlogDetailView.as_view()), name="blog_view"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main_app.urls", namespace="main_app")),
    path("blog/", include("blogs.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main_app.apps import MainAppConfig
from main_app.views import (
    ClientCreateView,
    ClientDeleteView,
    ClientDetailView,
    ClientListView,
    ClientUpdateView,
    LetterCreateView,
    LetterDeleteView,
    LetterDetailView,
    LetterListView,
    LetterUpdateView,
    LogMessageListView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingUpdateView,
    MainListView,
    ManagerListView,
    toggle_activity_mailing,
    toggle_activity_user,
)

app_name = MainAppConfig.name

urlpatterns = [
    path("", MainListView.as_view(), name="homepage"),
    path("manager/", ManagerListView.as_view(), name="manager"),
    path("user_activity/<int:pk>/", toggle_activity_user, name="toggle_activity_user"),

    path("clients/", ClientListView.as_view(), name="clients_page"),
    path("view_client/<int:pk>/", ClientDetailView.as_view(), name="view_client"),
    path("add_client/", ClientCreateView.as_view(), name="add_client"),
    path("update_client/<int:pk>/", ClientUpdateView.as_view(), name="update_client"),
    path("delete_client/<int:pk>/", ClientDeleteView.as_view(), name="delete_client"),

    path("letters/", LetterListView.as_view(), name="letters_page"),
    path("view_letter/<int:pk>/", LetterDetailView.as_view(), name="view_letter"),
    path("add_letter/", LetterCreateView.as_view(), name="add_letter"),
    path("update_letter/<int:pk>/", LetterUpdateView.as_view(), name="update_letter"),
    path("delete_letter/<int:pk>/", LetterDeleteView.as_view(), name="delete_letter"),

    path("view_log/<int:pk>/", cache_page(60)(LogMessageListView.as_view()), name="logs_page"),

    path("mailing/", MailingListView.as_view(), name="mailing_page"),
    path("view_mailing/<int:pk>/", MailingDetailView.as_view(), name="view_mailing"),
    path("add_mailing/", MailingCreateView.as_view(), name="add_mailing"),
    path("update_mailing/<int:pk>/", MailingUpdateView.as_view(), name="update_mailing"),
    path("delete_mailing/<int:pk>/", MailingDeleteView.as_view(), name="delete_mailing"),
    path("mailing_activity/<int:pk>/", toggle_activity_mailing, name="toggle_activity_mailing"),
]

main_app/models.py
from django.db import models
from django.utils import timezone

from config.settings import NULLABLE
from users.models import User


class Client(models.Model):
    """Модель клиента. Те кто получают рассылки"""

    email = models.EmailField(verbose_name="Email")
    name = models.CharField(max_length=150, verbose_name="ФИО клиента")
    comment = models.TextField(**NULLABLE, verbose_name="Комментарий")
    avatar = models.ImageField(**NULLABLE, upload_to="clients/", verbose_name="Аватар")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name="Владелец")

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Letter(models.Model):
    """Модель письма для рассылки"""

    letter_title = models.CharField(max_length=200, verbose_name="Тема письма")
    letter_body = models.TextField(verbose_name="Тело письма")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name="Владелец")

    def __str__(self):
        return f"{self.letter_title}"

    class Meta:
        verbose_name = "Письмо"
        verbose_name_plural = "Письма"


class Mailing(models.Model):
    """Модель рассылки"""

    DAILY = "Ежедневно"
    WEEKLY = "Еженедельно"
    MONTHLY = "Ежемесячно"

    PERIOD_CHOICES = {DAILY: "Ежедневно", WEEKLY: "Еженедельно", MONTHLY: "Ежемесячно"}

    CREATED = "Создана"
    STARTED = "Запущена"
    COMPLETED = "Завершена"

    STATUS_CHOICES = {CREATED: "Создана", STARTED: "Запущена", COMPLETED: "Завершена"}

    name = models.CharField(max_length=150, verbose_name="Имя рассылки")
    client_emails = models.ManyToManyField(Client, verbose_name="Emails")
    letter = models.ForeignKey(Letter, **NULLABLE, on_delete=models.SET, verbose_name="Письмо")
    first_sending_time = models.DateTimeField(**NULLABLE, verbose_name="Время первой рассылки")
    next_sending_time = models.DateTimeField(**NULLABLE, verbose_name="Время следующей рассылки")
    end_datetime = models.DateTimeField(**NULLABLE, verbose_name="Время остановки рассылки")
    period = models.CharField(max_length=150, choices=PERIOD_CHOICES, verbose_name="Период рассылки")
    status = models.CharField(
        default="Создана", max_length=20, **NULLABLE, choices=STATUS_CHOICES, verbose_name="Статус рассылки"
    )
    is_active = models.BooleanField(default=True, verbose_name="Активна")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name="Владелец")

    def __str__(self) -> str:
        return (
            f"{self.name}, {self.client_emails}, {self.letter},"
            f"{self.first_sending_time}, {self.end_datetime},"
            f"{self.period}, {self.status}, {self.is_active}"
        )

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"

        permissions = [("set_inactive", "Can block mailing")]


class LogMessage(models.Model):
    """Модель лога"""

    SENT = "Успешно"
    FAIL = "Безуспешно"

    LOG_CHOICES = {
        SENT: "Успешно",
        FAIL: "Безуспешно",
    }

    id_mailing = models.ForeignKey(Mailing, **NULLABLE, on_delete=models.CASCADE, verbose_name="Рассылка")
    last_try = models.DateTimeField(**NULLABLE, default=timezone.now, verbose_name="Время последней попытки")
    sending_status = models.CharField(max_length=10, choices=LOG_CHOICES, verbose_name="Статус лога")

    def __str__(self) -> str:
        return f"{self.last_try}, {self.id_mailing}, {self.sending_status}"

    class Meta:
        verbose_name = "Лог"
        verbose_name_plural = "Логи"

main_app/forms.py
from django import forms
from django.forms import BooleanField, DateTimeInput

from main_app.models import Client, Letter, Mailing


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ("created_by",)


class LetterForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Letter
        exclude = ("created_by",)


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = (
            "created_by",
            "status",
            "next_sending_time",
        )
        widgets = {
            "first_sending_time": DateTimeInput(attrs={"type": "datetime-local"}),
            "end_datetime": DateTimeInput(attrs={"type": "datetime-local"}),
        }
        labels = {
            "first_sending_time": "Время первой рассылки",
            "end_datetime": "Время остановки рассылки",
        }

main_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from blogs.models import Blog
from main_app.forms import ClientForm, LetterForm, MailingForm
from main_app.models import Client, Letter, LogMessage, Mailing
from main_app.services import get_cache_clients_count, get_cache_mailing_active, get_cache_mailing_count
from users.models import User


class MainListView(ListView):
    """Контроллер для главной страницы"""

    model = Blog
    template_name = "main_app/homepage.html"

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        return queryset[:3]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mailings_amount"] = get_cache_mailing_count()
        context["mailings_active"] = get_cache_mailing_active()
        context["clients_amount"] = get_cache_clients_count()
        return context


class ManagerListView(UserPassesTestMixin, ListView):
    """Контроллер для просмотра списка пользователей менеджером с возможностью их деактивации"""

    model = User
    template_name = "main_app/manager.html"

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if user.is_superuser:
            queryset = queryset
        else:
            queryset = queryset.filter(is_staff=False)
        return queryset


def toggle_activity_user(request, pk):
    """Функция для изменения статуса пользователя"""
    user_activity = get_object_or_404(User, pk=pk)
    if user_activity.is_active:
        user_activity.is_active = False
    else:
        user_activity.is_active = True
    user_activity.save()
    return redirect(reverse("main_app:manager"))


class ClientListView(LoginRequiredMixin, ListView):
    """Контроллер для вывода списка клиентов"""

    model = Client
    login_url = reverse_lazy("main_app:homepage")

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if user.is_superuser:
            queryset = queryset
        else:
            queryset = queryset.filter(created_by=self.request.user)
        return queryset


class ClientDetailView(DetailView):
    """Контроллер для просмотра клиента"""

    model = Client

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.created_by != user:
            raise Http404("Доступ запрещен")
        return self.object


class ClientCreateView(UserPassesTestMixin, CreateView):
    """Контроллер для создания клиента"""

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("main_app:clients_page")

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)

    def test_func(self):
        return not self.request.user.groups.filter(name="manager")


class ClientUpdateView(UpdateView):
    """Контроллер для изменения клиента"""

    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse("main_app:view_client", args=[self.kwargs.get("pk")])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.created_by != user:
            raise Http404("Доступ запрещен")
        return self.object


class ClientDeleteView(DeleteView):
    """Контроллер для удаления клиента"""

    model = Client
    success_url = reverse_lazy("main_app:clients_page")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.created_by != user:
            raise Http404("Доступ запрещен")
        return self.object


class LetterListView(LoginRequiredMixin, ListView):
    """Контроллер для вывода списка писем"""

    model = Letter
    login_url = reverse_lazy("main_app:homepage")

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if user.is_superuser:
            queryset = queryset
        else:
            queryset = queryset.filter(created_by=self.request.user)
        return queryset


class LetterDetailView(DetailView):
    """Контроллер для просмотра письма"""

    model = Letter

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.created_by != user:
            raise Http404("Доступ запрещен")
        return self.object


class LetterCreateView(UserPassesTestMixin, CreateView):
    """Контроллер для создания письма"""

    model = Letter
    form_class = LetterForm
    success_url = reverse_lazy("main_app:letters_page")

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)

    def test_func(self):
        return not self.request.user.groups.filter(name="manager")


class LetterUpdateView(UpdateView):
    """Контроллер для изменения письма"""

    model = Letter
    form_class = LetterForm

    def get_success_url(self):
        return reverse("main_app:view_letter", args=[self.kwargs.get("pk")])


class LetterDeleteView(DeleteView):
    """Контроллер для удаления письма"""

    model = Letter
    success_url = reverse_lazy("main_app:letters_page")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.created_by != user:
            raise Http404("Доступ запрещен")
        return self.object


class LogMessageListView(LoginRequiredMixin, ListView):
    """Контроллер для просмотра списка логов"""

    model = LogMessage
    login_url = reverse_lazy("users:login")

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(id_mailing=self.kwargs.get("pk"))
        return queryset


class MailingListView(LoginRequiredMixin, ListView):
    """Контроллер для вывода списка рассылок"""

    model = Mailing
    login_url = reverse_lazy("main_app:homepage")

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if user.groups.filter(name="manager") or user.is_superuser:
            queryset = queryset
        else:
            queryset = queryset.filter(created_by=self.request.user)
        return queryset


class MailingDetailView(DetailView):
    """Контроллер для просмотра рассылки"""

    model = Mailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.created_by != user and not user.groups.filter(name="manager"):
            raise Http404("Доступ запрещен")
        return self.object


class MailingCreateView(CreateView):
    """Контроллер для создания рассылки"""

    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("main_app:mailing_page")

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)

    def test_func(self):
        return not self.request.user.groups.filter(name="manager")


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер для изменения рассылки"""

    model = Mailing
    form_class = MailingForm
    login_url = reverse_lazy("main_app:homepage")

    def get_success_url(self):
        return reverse("main_app:view_mailing", args=[self.kwargs.get("pk")])

    def test_func(self):
        custom_perms = ("mailing.set_inactive",)
        if self.request.user.groups.filter(name="manager") and self.request.user.has_perms(custom_perms):
            return True
        return self.handle_no_permission()

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.created_by != user:
            raise Http404("Доступ запрещен")
        return self.object


class MailingDeleteView(DeleteView):
    """Контроллер для удаления рассылки"""

    model = Mailing
    success_url = reverse_lazy("main_app:mailing_page")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and self.object.created_by != user:
            raise Http404("Доступ запрещен")
        return self.object


def toggle_activity_mailing(request, pk):
    """Контроллер для изменения статуса рассылки"""
    mailing_status = get_object_or_404(Mailing, pk=pk)
    if mailing_status.is_active:
        mailing_status.is_active = False
    else:
        mailing_status.is_active = True
    mailing_status.save()
    return redirect(reverse("main_app:mailing_page"))

main_app/templates/main_app/client_confirm_delete.html
{% extends 'main_app/base.html' %}

{% block content %}

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Удаление клиента</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Точно удаляем ?</p>
                    <p>{{ object.email|title }}</p>
                    <p>{{ object.name|title }}</p>
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-danger">Удалить</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'main_app:clients_page' %}" class="w-100 btn btn-lg btn-outline-primary">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/client_detail.html
{% extends 'main_app/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.name|title }}</h1>
</div>
<div class="row row-cols-1 row-cols-md-2 mb-2 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-body">
                <img class="card-img-top" src="/media/{{ object.avatar }}" alt="Item image">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Email: {{ object.email }}</li>
                    <li>Комментарий: {{ object.comment }}</li>
                    <li>Владелец: {{ object.created_by }}</li>
                </ul>
                <div class="mb-3">
                    <a href="{% url 'main_app:update_client' object.pk %}" class="w-100 btn btn-lg btn-outline-primary">Редактировать</a>
                </div>
                <div class="mb-3">
                    <a href="{% url 'main_app:delete_client' object.pk %}" class="w-100 btn btn-lg btn-outline-danger">Удалить</a>
                </div>
                <div class="mb-3">
                    <a href="{% url 'main_app:clients_page' %}" class="w-100 btn btn-lg btn-outline-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/client_list.html
{% extends 'main_app/base.html' %}

{% block content %}

<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-2 rounded-3 shadow-sm border-primary">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">{{ object.name|title }}</h6>
                </div>
                <div class="card-body">
                    <h6 class="card-title pricing-card-title">Email: {{ object.email }}</h6>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Владелец: {{ object.created_by }}</li>
                    </ul>
                    <a href="{% url 'main_app:view_client' object.pk %}" class="w-120 btn btn-lg btn-outline-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% if not user.is_staff %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">Новый клиент</h6>
                </div>
                <div class="card-body">
                    <a href="{% url 'main_app:add_client' %}" class="w-120 btn btn-lg btn-outline-primary">Добавить</a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</main>

{% endblock %}

main_app/templates/main_app/letter_detail.html
{% extends 'main_app/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object|title }}</h1>
</div>

<div class="row row-cols-1 row-cols-md-2 mb-2 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Текст письма: {{ object.letter_body }}</li>
                    <li>Владелец: {{ object.created_by }}</li>
                </ul>
                <div class="mb-3">
                    <a href="{% url 'main_app:update_letter' object.pk %}" class="w-100 btn btn-lg btn-outline-primary">Редактировать</a>
                </div>
                <div class="mb-3">
                    <a href="{% url 'main_app:delete_letter' object.pk %}" class="w-100 btn btn-lg btn-outline-danger">Удалить</a>
                </div>
                <div class="mb-3">
                    <a href="{% url 'main_app:letters_page' %}" class="w-100 btn btn-lg btn-outline-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/letter_list.html
{% extends 'main_app/base.html' %}

{% block content %}

<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">{{ object|capfirst }}</h6>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Владелец: {{ object.created_by }}</li>
                    </ul>
                    <a href="{% url 'main_app:view_letter' object.pk %}" class="w-120 btn btn-lg btn-outline-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% if not user.is_staff %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">Новое письмо</h6>
                </div>
                <div class="card-body">
                    <a href="{% url 'main_app:add_letter' %}" class="w-120 btn btn-lg btn-outline-primary">Добавить</a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</main>

{% endblock %}

main_app/templates/main_app/mailing_detail.html
{% extends 'main_app/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылка: {{ object.name|title }}</h1>
</div>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Тема письма: {{ object.letter }}</li>
                    <li>Время начала рассылки: {{ object.first_sending_time|date:"d/m/Y, H:i" }}</li>
                    <li>Период: {{ object.period }}</li>
                    <li>Время конца: {{ object.end_datetime|date:"d/m/Y, H:i" }}</li>
                    <li>Владелец: {{ object.created_by }}</li>
                    <li>Клиенты: {% for client in object.client_emails.all %} {{ client.email }}</li> {% endfor %}
                </ul>
                {% if user.is_superuser or user == object.created_by %}
                <div class="mb-3">
                    <a href="{% url 'main_app:update_mailing' object.pk %}" class="w-100 btn btn-lg btn-outline-primary">Редактировать</a>
                </div>
                <div class="mb-3">
                    <a href="{% url 'main_app:delete_mailing' object.pk %}" class="w-100 btn btn-lg btn-outline-danger">Удалить</a>
                </div>
                {% endif %}
                <div class="mb-3">
                    <a href="{% url 'main_app:mailing_page' %}" class="w-100 btn btn-lg btn-outline-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/mailing_list.html
{% extends 'main_app/base.html' %}

{% block content %}

<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-2 rounded-3 shadow-sm border-primary">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">{{ object.name|title }}</h6>
                </div>
                <div class="card-body">
                    <h6 class="card-title pricing-card-title">Время рассылки: {{ object.first_sending_time|date:"d/m/Y, H:i" }}</h6>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Периодичность: {{ object.period }}</li>
                        <li>Статус: {{ object.status }}</li>
                        <li>Владелец: {{ object.created_by }}</li>
                        <li>След рассылка: {{ object.next_sending_time|date:"d/m/Y, H:i"|default:'Не заполнено'}}</li>
                    </ul>
                    <div class="mb-3">
                        {% if object.is_active %}
                        <a href="{% url 'main_app:toggle_activity_mailing' object.pk %}"
                           class="w-120 btn btn-lg btn-outline-danger">Отключить</a>
                        {% else %}
                        <a href="{% url 'main_app:toggle_activity_mailing' object.pk %}"
                           class="w-120 btn btn-lg btn-outline-success">Включить</a>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'main_app:logs_page' object.pk %}"
                           class="w-120 btn btn-lg btn-outline-warning">Логи</a>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'main_app:view_mailing' object.pk %}"
                           class="w-120 btn btn-lg btn-outline-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% if not user.is_staff %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-2 text-white bg-primary border-primary">
                    <h6 class="my-0 fw-normal text text-truncate">Новая рассылка</h6>
                </div>
                <div class="card-body">
                    <a href="{% url 'main_app:add_mailing' %}" class="w-120 btn btn-lg btn-outline-primary">Добавить</a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</main>

{% endblock %}